### ISSUE TITLE
License

### ISSUE THREAD

**Issue by paulthorsteinson** [ateska/ios-csr#1]
Hello, 
This is a fantastic example of generating a CSR which is very hard to find on iOS, especially without using openssl.  Fantastic work!
Would you guys consider changing the license to MIT.  It is much more flexible and GPLv2 requires the entire project to become GPLv2 which is not possible a lot of time time.  Thanks for your consideration.

http://stackoverflow.com/questions/3902754/mit-vs-gpl-license

**Comment by taylortrimble** [comment]
I need this as well. I would love to use this code, but this license technically does not allow me to link it into my app without changing my app's license to GPLv2.

Additionally, since [the GPL is incompatible with the terms of the iOS App Store](http://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement), no app that uses this library is eligible for the App Store.

I would also recommend an MIT license.

**Comment by cbaker6** [comment]
@paulthorsteinson @tylrtrmbl I have created a CSR Swift framework that uses an MIT license. It's possible that it could help both of you, https://github.com/cbaker6/iOS-csr-swift

**Comment by benaubin** [comment]
@ateska Could you change this to an MIT or Apache license? A GPL means you have to release your source code along with other issues that makes it difficult to use in the App Store. This looks like a great library and I'd love to be able to use it.

**Comment by wuf810** [comment]
+1

**Comment by benaubin** [comment]
@JohnyMnemonic I'm tagging you as well as it would be great if you could relicense your code you contributed to this library. 

CC @ateska
